spring.application.name=study-scheduling-engine

spring.datasource.url=jdbc:mysql://localhost:3306/study_scheduler
spring.datasource.username=root
spring.datasource.password=Resh_515

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true